//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PhixDataFlow.sforce {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapBinding", Namespace="urn:partner.soap.sforce.com")]
    public partial class SforceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private CallOptions callOptionsValueField;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private SessionHeader sessionHeaderValueField;
        
        private System.Threading.SendOrPostCallback describeSObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback describeGlobalOperationCompleted;
        
        private SaveOptions saveOptionsValueField;
        
        private System.Threading.SendOrPostCallback createOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteOperationCompleted;
        
        private QueryOptions queryOptionsValueField;
        
        private System.Threading.SendOrPostCallback retrieveOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDeletedOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryMoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getServerTimestampOperationCompleted;
        
        private System.Threading.SendOrPostCallback setPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SforceService() {
            this.Url = global::PhixDataFlow.Properties.Settings.Default.PhixDataFlow_sforce_SforceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public CallOptions CallOptionsValue {
            get {
                return this.callOptionsValueField;
            }
            set {
                this.callOptionsValueField = value;
            }
        }
        
        public SessionHeader SessionHeaderValue {
            get {
                return this.sessionHeaderValueField;
            }
            set {
                this.sessionHeaderValueField = value;
            }
        }
        
        public SaveOptions SaveOptionsValue {
            get {
                return this.saveOptionsValueField;
            }
            set {
                this.saveOptionsValueField = value;
            }
        }
        
        public QueryOptions QueryOptionsValue {
            get {
                return this.queryOptionsValueField;
            }
            set {
                this.queryOptionsValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event describeSObjectCompletedEventHandler describeSObjectCompleted;
        
        /// <remarks/>
        public event describeGlobalCompletedEventHandler describeGlobalCompleted;
        
        /// <remarks/>
        public event createCompletedEventHandler createCompleted;
        
        /// <remarks/>
        public event updateCompletedEventHandler updateCompleted;
        
        /// <remarks/>
        public event deleteCompletedEventHandler deleteCompleted;
        
        /// <remarks/>
        public event retrieveCompletedEventHandler retrieveCompleted;
        
        /// <remarks/>
        public event getDeletedCompletedEventHandler getDeletedCompleted;
        
        /// <remarks/>
        public event getUpdatedCompletedEventHandler getUpdatedCompleted;
        
        /// <remarks/>
        public event queryCompletedEventHandler queryCompleted;
        
        /// <remarks/>
        public event queryMoreCompletedEventHandler queryMoreCompleted;
        
        /// <remarks/>
        public event searchCompletedEventHandler searchCompleted;
        
        /// <remarks/>
        public event getServerTimestampCompletedEventHandler getServerTimestampCompleted;
        
        /// <remarks/>
        public event setPasswordCompletedEventHandler setPasswordCompleted;
        
        /// <remarks/>
        public event resetPasswordCompletedEventHandler resetPasswordCompleted;
        
        /// <remarks/>
        public event getUserInfoCompletedEventHandler getUserInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public LoginResult login(string username, string password) {
            object[] results = this.Invoke("login", new object[] {
                        username,
                        password});
            return ((LoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password) {
            this.loginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string username, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        username,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DescribeSObjectResult describeSObject(string sObjectType) {
            object[] results = this.Invoke("describeSObject", new object[] {
                        sObjectType});
            return ((DescribeSObjectResult)(results[0]));
        }
        
        /// <remarks/>
        public void describeSObjectAsync(string sObjectType) {
            this.describeSObjectAsync(sObjectType, null);
        }
        
        /// <remarks/>
        public void describeSObjectAsync(string sObjectType, object userState) {
            if ((this.describeSObjectOperationCompleted == null)) {
                this.describeSObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescribeSObjectOperationCompleted);
            }
            this.InvokeAsync("describeSObject", new object[] {
                        sObjectType}, this.describeSObjectOperationCompleted, userState);
        }
        
        private void OndescribeSObjectOperationCompleted(object arg) {
            if ((this.describeSObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.describeSObjectCompleted(this, new describeSObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DescribeGlobalResult describeGlobal() {
            object[] results = this.Invoke("describeGlobal", new object[0]);
            return ((DescribeGlobalResult)(results[0]));
        }
        
        /// <remarks/>
        public void describeGlobalAsync() {
            this.describeGlobalAsync(null);
        }
        
        /// <remarks/>
        public void describeGlobalAsync(object userState) {
            if ((this.describeGlobalOperationCompleted == null)) {
                this.describeGlobalOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescribeGlobalOperationCompleted);
            }
            this.InvokeAsync("describeGlobal", new object[0], this.describeGlobalOperationCompleted, userState);
        }
        
        private void OndescribeGlobalOperationCompleted(object arg) {
            if ((this.describeGlobalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.describeGlobalCompleted(this, new describeGlobalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SaveOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public SaveResult[] create([System.Xml.Serialization.XmlElementAttribute("sObjects")] sObject[] sObjects) {
            object[] results = this.Invoke("create", new object[] {
                        sObjects});
            return ((SaveResult[])(results[0]));
        }
        
        /// <remarks/>
        public void createAsync(sObject[] sObjects) {
            this.createAsync(sObjects, null);
        }
        
        /// <remarks/>
        public void createAsync(sObject[] sObjects, object userState) {
            if ((this.createOperationCompleted == null)) {
                this.createOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateOperationCompleted);
            }
            this.InvokeAsync("create", new object[] {
                        sObjects}, this.createOperationCompleted, userState);
        }
        
        private void OncreateOperationCompleted(object arg) {
            if ((this.createCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createCompleted(this, new createCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SaveOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public SaveResult[] update([System.Xml.Serialization.XmlElementAttribute("sObjects")] sObject[] sObjects) {
            object[] results = this.Invoke("update", new object[] {
                        sObjects});
            return ((SaveResult[])(results[0]));
        }
        
        /// <remarks/>
        public void updateAsync(sObject[] sObjects) {
            this.updateAsync(sObjects, null);
        }
        
        /// <remarks/>
        public void updateAsync(sObject[] sObjects, object userState) {
            if ((this.updateOperationCompleted == null)) {
                this.updateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateOperationCompleted);
            }
            this.InvokeAsync("update", new object[] {
                        sObjects}, this.updateOperationCompleted, userState);
        }
        
        private void OnupdateOperationCompleted(object arg) {
            if ((this.updateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompleted(this, new updateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public DeleteResult[] delete([System.Xml.Serialization.XmlElementAttribute("ids")] string[] ids) {
            object[] results = this.Invoke("delete", new object[] {
                        ids});
            return ((DeleteResult[])(results[0]));
        }
        
        /// <remarks/>
        public void deleteAsync(string[] ids) {
            this.deleteAsync(ids, null);
        }
        
        /// <remarks/>
        public void deleteAsync(string[] ids, object userState) {
            if ((this.deleteOperationCompleted == null)) {
                this.deleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteOperationCompleted);
            }
            this.InvokeAsync("delete", new object[] {
                        ids}, this.deleteOperationCompleted, userState);
        }
        
        private void OndeleteOperationCompleted(object arg) {
            if ((this.deleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteCompleted(this, new deleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public sObject[] retrieve(string fieldList, string sObjectType, [System.Xml.Serialization.XmlElementAttribute("ids")] string[] ids) {
            object[] results = this.Invoke("retrieve", new object[] {
                        fieldList,
                        sObjectType,
                        ids});
            return ((sObject[])(results[0]));
        }
        
        /// <remarks/>
        public void retrieveAsync(string fieldList, string sObjectType, string[] ids) {
            this.retrieveAsync(fieldList, sObjectType, ids, null);
        }
        
        /// <remarks/>
        public void retrieveAsync(string fieldList, string sObjectType, string[] ids, object userState) {
            if ((this.retrieveOperationCompleted == null)) {
                this.retrieveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveOperationCompleted);
            }
            this.InvokeAsync("retrieve", new object[] {
                        fieldList,
                        sObjectType,
                        ids}, this.retrieveOperationCompleted, userState);
        }
        
        private void OnretrieveOperationCompleted(object arg) {
            if ((this.retrieveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveCompleted(this, new retrieveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public GetDeletedResult getDeleted(string sObjectType, System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("getDeleted", new object[] {
                        sObjectType,
                        startDate,
                        endDate});
            return ((GetDeletedResult)(results[0]));
        }
        
        /// <remarks/>
        public void getDeletedAsync(string sObjectType, System.DateTime startDate, System.DateTime endDate) {
            this.getDeletedAsync(sObjectType, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void getDeletedAsync(string sObjectType, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.getDeletedOperationCompleted == null)) {
                this.getDeletedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDeletedOperationCompleted);
            }
            this.InvokeAsync("getDeleted", new object[] {
                        sObjectType,
                        startDate,
                        endDate}, this.getDeletedOperationCompleted, userState);
        }
        
        private void OngetDeletedOperationCompleted(object arg) {
            if ((this.getDeletedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDeletedCompleted(this, new getDeletedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public GetUpdatedResult getUpdated(string sObjectType, System.DateTime startDate, System.DateTime endDate) {
            object[] results = this.Invoke("getUpdated", new object[] {
                        sObjectType,
                        startDate,
                        endDate});
            return ((GetUpdatedResult)(results[0]));
        }
        
        /// <remarks/>
        public void getUpdatedAsync(string sObjectType, System.DateTime startDate, System.DateTime endDate) {
            this.getUpdatedAsync(sObjectType, startDate, endDate, null);
        }
        
        /// <remarks/>
        public void getUpdatedAsync(string sObjectType, System.DateTime startDate, System.DateTime endDate, object userState) {
            if ((this.getUpdatedOperationCompleted == null)) {
                this.getUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUpdatedOperationCompleted);
            }
            this.InvokeAsync("getUpdated", new object[] {
                        sObjectType,
                        startDate,
                        endDate}, this.getUpdatedOperationCompleted, userState);
        }
        
        private void OngetUpdatedOperationCompleted(object arg) {
            if ((this.getUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUpdatedCompleted(this, new getUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public QueryResult query(string queryString) {
            object[] results = this.Invoke("query", new object[] {
                        queryString});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryAsync(string queryString) {
            this.queryAsync(queryString, null);
        }
        
        /// <remarks/>
        public void queryAsync(string queryString, object userState) {
            if ((this.queryOperationCompleted == null)) {
                this.queryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryOperationCompleted);
            }
            this.InvokeAsync("query", new object[] {
                        queryString}, this.queryOperationCompleted, userState);
        }
        
        private void OnqueryOperationCompleted(object arg) {
            if ((this.queryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCompleted(this, new queryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("QueryOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public QueryResult queryMore(string queryLocator) {
            object[] results = this.Invoke("queryMore", new object[] {
                        queryLocator});
            return ((QueryResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryMoreAsync(string queryLocator) {
            this.queryMoreAsync(queryLocator, null);
        }
        
        /// <remarks/>
        public void queryMoreAsync(string queryLocator, object userState) {
            if ((this.queryMoreOperationCompleted == null)) {
                this.queryMoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryMoreOperationCompleted);
            }
            this.InvokeAsync("queryMore", new object[] {
                        queryLocator}, this.queryMoreOperationCompleted, userState);
        }
        
        private void OnqueryMoreOperationCompleted(object arg) {
            if ((this.queryMoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryMoreCompleted(this, new queryMoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public SearchResult search(string searchString) {
            object[] results = this.Invoke("search", new object[] {
                        searchString});
            return ((SearchResult)(results[0]));
        }
        
        /// <remarks/>
        public void searchAsync(string searchString) {
            this.searchAsync(searchString, null);
        }
        
        /// <remarks/>
        public void searchAsync(string searchString, object userState) {
            if ((this.searchOperationCompleted == null)) {
                this.searchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchOperationCompleted);
            }
            this.InvokeAsync("search", new object[] {
                        searchString}, this.searchOperationCompleted, userState);
        }
        
        private void OnsearchOperationCompleted(object arg) {
            if ((this.searchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchCompleted(this, new searchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public GetServerTimestampResult getServerTimestamp() {
            object[] results = this.Invoke("getServerTimestamp", new object[0]);
            return ((GetServerTimestampResult)(results[0]));
        }
        
        /// <remarks/>
        public void getServerTimestampAsync() {
            this.getServerTimestampAsync(null);
        }
        
        /// <remarks/>
        public void getServerTimestampAsync(object userState) {
            if ((this.getServerTimestampOperationCompleted == null)) {
                this.getServerTimestampOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetServerTimestampOperationCompleted);
            }
            this.InvokeAsync("getServerTimestamp", new object[0], this.getServerTimestampOperationCompleted, userState);
        }
        
        private void OngetServerTimestampOperationCompleted(object arg) {
            if ((this.getServerTimestampCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getServerTimestampCompleted(this, new getServerTimestampCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public SetPasswordResult setPassword(string userId, string password) {
            object[] results = this.Invoke("setPassword", new object[] {
                        userId,
                        password});
            return ((SetPasswordResult)(results[0]));
        }
        
        /// <remarks/>
        public void setPasswordAsync(string userId, string password) {
            this.setPasswordAsync(userId, password, null);
        }
        
        /// <remarks/>
        public void setPasswordAsync(string userId, string password, object userState) {
            if ((this.setPasswordOperationCompleted == null)) {
                this.setPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetPasswordOperationCompleted);
            }
            this.InvokeAsync("setPassword", new object[] {
                        userId,
                        password}, this.setPasswordOperationCompleted, userState);
        }
        
        private void OnsetPasswordOperationCompleted(object arg) {
            if ((this.setPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setPasswordCompleted(this, new setPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public ResetPasswordResult resetPassword(string userId) {
            object[] results = this.Invoke("resetPassword", new object[] {
                        userId});
            return ((ResetPasswordResult)(results[0]));
        }
        
        /// <remarks/>
        public void resetPasswordAsync(string userId) {
            this.resetPasswordAsync(userId, null);
        }
        
        /// <remarks/>
        public void resetPasswordAsync(string userId, object userState) {
            if ((this.resetPasswordOperationCompleted == null)) {
                this.resetPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetPasswordOperationCompleted);
            }
            this.InvokeAsync("resetPassword", new object[] {
                        userId}, this.resetPasswordOperationCompleted, userState);
        }
        
        private void OnresetPasswordOperationCompleted(object arg) {
            if ((this.resetPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetPasswordCompleted(this, new resetPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("CallOptionsValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SessionHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:partner.soap.sforce.com", ResponseNamespace="urn:partner.soap.sforce.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public GetUserInfoResult getUserInfo() {
            object[] results = this.Invoke("getUserInfo", new object[0]);
            return ((GetUserInfoResult)(results[0]));
        }
        
        /// <remarks/>
        public void getUserInfoAsync() {
            this.getUserInfoAsync(null);
        }
        
        /// <remarks/>
        public void getUserInfoAsync(object userState) {
            if ((this.getUserInfoOperationCompleted == null)) {
                this.getUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserInfoOperationCompleted);
            }
            this.InvokeAsync("getUserInfo", new object[0], this.getUserInfoOperationCompleted, userState);
        }
        
        private void OngetUserInfoOperationCompleted(object arg) {
            if ((this.getUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserInfoCompleted(this, new getUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:partner.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:partner.soap.sforce.com", IsNullable=false)]
    public partial class SessionHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string sessionIdField;
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class GetUserInfoResult {
        
        private string currencySymbolField;
        
        private bool organizationMultiCurrencyField;
        
        private string organizationIdField;
        
        private string organizationNameField;
        
        private string userDefaultCurrencyIsoCodeField;
        
        private string userEmailField;
        
        private string userFullNameField;
        
        private string userIdField;
        
        private string userLanguageField;
        
        private string userLocaleField;
        
        private string userTimeZoneField;
        
        /// <remarks/>
        public string currencySymbol {
            get {
                return this.currencySymbolField;
            }
            set {
                this.currencySymbolField = value;
            }
        }
        
        /// <remarks/>
        public bool organizationMultiCurrency {
            get {
                return this.organizationMultiCurrencyField;
            }
            set {
                this.organizationMultiCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public string organizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public string organizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string userDefaultCurrencyIsoCode {
            get {
                return this.userDefaultCurrencyIsoCodeField;
            }
            set {
                this.userDefaultCurrencyIsoCodeField = value;
            }
        }
        
        /// <remarks/>
        public string userEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public string userFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string userLanguage {
            get {
                return this.userLanguageField;
            }
            set {
                this.userLanguageField = value;
            }
        }
        
        /// <remarks/>
        public string userLocale {
            get {
                return this.userLocaleField;
            }
            set {
                this.userLocaleField = value;
            }
        }
        
        /// <remarks/>
        public string userTimeZone {
            get {
                return this.userTimeZoneField;
            }
            set {
                this.userTimeZoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class ResetPasswordResult {
        
        private string passwordField;
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class SetPasswordResult {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class GetServerTimestampResult {
        
        private System.DateTime timestampField;
        
        /// <remarks/>
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class SearchRecord {
        
        private sObject recordField;
        
        /// <remarks/>
        public sObject record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sobject.partner.soap.sforce.com")]
    public partial class sObject {
        
        private string typeField;
        
        private string[] fieldsToNullField;
        
        private string idField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fieldsToNull", IsNullable=true)]
        public string[] fieldsToNull {
            get {
                return this.fieldsToNullField;
            }
            set {
                this.fieldsToNullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class SearchResult {
        
        private SearchRecord[] searchRecordsField;
        
        private string sforceReservedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchRecords")]
        public SearchRecord[] searchRecords {
            get {
                return this.searchRecordsField;
            }
            set {
                this.searchRecordsField = value;
            }
        }
        
        /// <remarks/>
        public string sforceReserved {
            get {
                return this.sforceReservedField;
            }
            set {
                this.sforceReservedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class QueryResult {
        
        private bool doneField;
        
        private string queryLocatorField;
        
        private sObject[] recordsField;
        
        private int sizeField;
        
        /// <remarks/>
        public bool done {
            get {
                return this.doneField;
            }
            set {
                this.doneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryLocator {
            get {
                return this.queryLocatorField;
            }
            set {
                this.queryLocatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("records", IsNullable=true)]
        public sObject[] records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
        
        /// <remarks/>
        public int size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class GetUpdatedResult {
        
        private string[] idsField;
        
        private string sforceReservedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ids")]
        public string[] ids {
            get {
                return this.idsField;
            }
            set {
                this.idsField = value;
            }
        }
        
        /// <remarks/>
        public string sforceReserved {
            get {
                return this.sforceReservedField;
            }
            set {
                this.sforceReservedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class DeletedRecord {
        
        private string idField;
        
        private System.DateTime deletedDateField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime deletedDate {
            get {
                return this.deletedDateField;
            }
            set {
                this.deletedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class GetDeletedResult {
        
        private DeletedRecord[] deletedRecordsField;
        
        private string sforceReservedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deletedRecords")]
        public DeletedRecord[] deletedRecords {
            get {
                return this.deletedRecordsField;
            }
            set {
                this.deletedRecordsField = value;
            }
        }
        
        /// <remarks/>
        public string sforceReserved {
            get {
                return this.sforceReservedField;
            }
            set {
                this.sforceReservedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class DeleteResult {
        
        private Error[] errorsField;
        
        private string idField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", IsNullable=true)]
        public Error[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class Error {
        
        private string[] fieldsField;
        
        private string messageField;
        
        private StatusCode statusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", IsNullable=true)]
        public string[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public StatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public enum StatusCode {
        
        /// <remarks/>
        ASSIGNEE_TYPE_REQUIRED,
        
        /// <remarks/>
        CANNOT_CASCADE_PRODUCT_ACTIVE,
        
        /// <remarks/>
        CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY,
        
        /// <remarks/>
        CANNOT_REPARENT_RECORD,
        
        /// <remarks/>
        CANNOT_RESOLVE_NAME,
        
        /// <remarks/>
        CANNOT_UPDATE_CONVERTED_LEAD,
        
        /// <remarks/>
        CANT_DISABLE_CORP_CURRENCY,
        
        /// <remarks/>
        CANT_UNSET_CORP_CURRENCY,
        
        /// <remarks/>
        CHILD_SHARE_FAILS_PARENT,
        
        /// <remarks/>
        CIRCULAR_DEPENDENCY,
        
        /// <remarks/>
        CUSTOM_ENTITY_OR_FIELD_LIMIT,
        
        /// <remarks/>
        CUSTOM_FIELD_INDEX_LIMIT_EXCEEDED,
        
        /// <remarks/>
        DELETE_FAILED,
        
        /// <remarks/>
        DEPENDENCY_EXISTS,
        
        /// <remarks/>
        DUPLICATE_CASE_SOLUTION,
        
        /// <remarks/>
        DUPLICATE_DEVELOPER_NAME,
        
        /// <remarks/>
        DUPLICATE_MASTER_LABEL,
        
        /// <remarks/>
        DUPLICATE_USERNAME,
        
        /// <remarks/>
        DUPLICATE_VALUE,
        
        /// <remarks/>
        ENTITY_FAILED_IFLASTMODIFIED_ON_UPDATE,
        
        /// <remarks/>
        ENTITY_IS_ARCHIVED,
        
        /// <remarks/>
        ENTITY_IS_DELETED,
        
        /// <remarks/>
        ENTITY_IS_LOCKED,
        
        /// <remarks/>
        FAILED_ACTIVATION,
        
        /// <remarks/>
        FIELD_INTEGRITY_EXCEPTION,
        
        /// <remarks/>
        INACTIVE_OWNER_OR_USER,
        
        /// <remarks/>
        INSUFFICIENT_ACCESS_ON_CROSS_REFERENCE_ENTITY,
        
        /// <remarks/>
        INSUFFICIENT_ACCESS_OR_READONLY,
        
        /// <remarks/>
        INVALID_ACCESS_LEVEL,
        
        /// <remarks/>
        INVALID_ARGUMENT_TYPE,
        
        /// <remarks/>
        INVALID_ASSIGNEE_TYPE,
        
        /// <remarks/>
        INVALID_ASSIGNMENT_RULE,
        
        /// <remarks/>
        INVALID_BATCH_OPERATION,
        
        /// <remarks/>
        INVALID_CREDIT_CARD_INFO,
        
        /// <remarks/>
        INVALID_CROSS_REFERENCE_KEY,
        
        /// <remarks/>
        INVALID_CROSS_REFERENCE_TYPE_FOR_FIELD,
        
        /// <remarks/>
        INVALID_CURRENCY_ISO,
        
        /// <remarks/>
        INVALID_EMAIL_ADDRESS,
        
        /// <remarks/>
        INVALID_EMPTY_KEY_OWNER,
        
        /// <remarks/>
        INVALID_FIELD_FOR_INSERT_UPDATE,
        
        /// <remarks/>
        INVALID_FILTER_ACTION,
        
        /// <remarks/>
        INVALID_ID_FIELD,
        
        /// <remarks/>
        INVALID_LINEITEM_CLONE_STATE,
        
        /// <remarks/>
        INVALID_OPERATOR,
        
        /// <remarks/>
        INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST,
        
        /// <remarks/>
        INVALID_STATUS,
        
        /// <remarks/>
        INVALID_TYPE,
        
        /// <remarks/>
        INVALID_TYPE_FOR_OPERATION,
        
        /// <remarks/>
        INVALID_TYPE_ON_FIELD_IN_RECORD,
        
        /// <remarks/>
        LAST_MODIFIED_SINCE_TOO_OLD,
        
        /// <remarks/>
        LICENSE_LIMIT_EXCEEDED,
        
        /// <remarks/>
        MALFORMED_ID,
        
        /// <remarks/>
        MAXIMUM_CCEMAILS_EXCEEDED,
        
        /// <remarks/>
        MAXIMUM_DASHBOARD_COMPONENTS_EXCEEDED,
        
        /// <remarks/>
        MAXIMUM_SIZE_OF_ATTACHMENT,
        
        /// <remarks/>
        MAXIMUM_SIZE_OF_DOCUMENT,
        
        /// <remarks/>
        MAX_ACTIONS_PER_RULE_EXCEEDED,
        
        /// <remarks/>
        MAX_ACTIVE_RULES_EXCEEDED,
        
        /// <remarks/>
        MAX_TASK_DESCRIPTION_EXCEEEDED,
        
        /// <remarks/>
        MISSING_ARGUMENT,
        
        /// <remarks/>
        NUMBER_OUTSIDE_VALID_RANGE,
        
        /// <remarks/>
        REQUIRED_FIELD_MISSING,
        
        /// <remarks/>
        SHARE_NEEDED_FOR_CHILD_OWNER,
        
        /// <remarks/>
        STANDARD_PRICE_NOT_DEFINED,
        
        /// <remarks/>
        STORAGE_LIMIT_EXCEEDED,
        
        /// <remarks/>
        TEXT_DATA_OUTSIDE_SUPPORTED_CHARSET,
        
        /// <remarks/>
        UNKNOWN_EXCEPTION,
        
        /// <remarks/>
        UNSPECIFIED_EMAIL_ADDRESS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class SaveResult {
        
        private Error[] errorsField;
        
        private string idField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", IsNullable=true)]
        public Error[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class DescribeGlobalResult {
        
        private string encodingField;
        
        private int maxBatchSizeField;
        
        private string[] typesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        public int maxBatchSize {
            get {
                return this.maxBatchSizeField;
            }
            set {
                this.maxBatchSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("types", IsNullable=true)]
        public string[] types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class PicklistEntry {
        
        private bool activeField;
        
        private bool defaultValueField;
        
        private string labelField;
        
        private string valueField;
        
        /// <remarks/>
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public bool defaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class Field {
        
        private int byteLengthField;
        
        private bool createableField;
        
        private bool customField;
        
        private int digitsField;
        
        private bool filterableField;
        
        private string labelField;
        
        private int lengthField;
        
        private string nameField1;
        
        private bool nameFieldField;
        
        private bool nillableField;
        
        private PicklistEntry[] picklistValuesField;
        
        private int precisionField;
        
        private string[] referenceToField;
        
        private bool restrictedPicklistField;
        
        private int scaleField;
        
        private soapType soapTypeField;
        
        private fieldType typeField;
        
        private bool updateableField;
        
        /// <remarks/>
        public int byteLength {
            get {
                return this.byteLengthField;
            }
            set {
                this.byteLengthField = value;
            }
        }
        
        /// <remarks/>
        public bool createable {
            get {
                return this.createableField;
            }
            set {
                this.createableField = value;
            }
        }
        
        /// <remarks/>
        public bool custom {
            get {
                return this.customField;
            }
            set {
                this.customField = value;
            }
        }
        
        /// <remarks/>
        public int digits {
            get {
                return this.digitsField;
            }
            set {
                this.digitsField = value;
            }
        }
        
        /// <remarks/>
        public bool filterable {
            get {
                return this.filterableField;
            }
            set {
                this.filterableField = value;
            }
        }
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public int length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField1;
            }
            set {
                this.nameField1 = value;
            }
        }
        
        /// <remarks/>
        public bool nameField {
            get {
                return this.nameFieldField;
            }
            set {
                this.nameFieldField = value;
            }
        }
        
        /// <remarks/>
        public bool nillable {
            get {
                return this.nillableField;
            }
            set {
                this.nillableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("picklistValues", IsNullable=true)]
        public PicklistEntry[] picklistValues {
            get {
                return this.picklistValuesField;
            }
            set {
                this.picklistValuesField = value;
            }
        }
        
        /// <remarks/>
        public int precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("referenceTo", IsNullable=true)]
        public string[] referenceTo {
            get {
                return this.referenceToField;
            }
            set {
                this.referenceToField = value;
            }
        }
        
        /// <remarks/>
        public bool restrictedPicklist {
            get {
                return this.restrictedPicklistField;
            }
            set {
                this.restrictedPicklistField = value;
            }
        }
        
        /// <remarks/>
        public int scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        public soapType soapType {
            get {
                return this.soapTypeField;
            }
            set {
                this.soapTypeField = value;
            }
        }
        
        /// <remarks/>
        public fieldType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public bool updateable {
            get {
                return this.updateableField;
            }
            set {
                this.updateableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public enum soapType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("tns:ID")]
        tnsID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:base64Binary")]
        xsdbase64Binary,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:boolean")]
        xsdboolean,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:double")]
        xsddouble,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:int")]
        xsdint,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:string")]
        xsdstring,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:date")]
        xsddate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("xsd:dateTime")]
        xsddateTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public enum fieldType {
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        picklist,
        
        /// <remarks/>
        combobox,
        
        /// <remarks/>
        reference,
        
        /// <remarks/>
        base64,
        
        /// <remarks/>
        boolean,
        
        /// <remarks/>
        currency,
        
        /// <remarks/>
        textarea,
        
        /// <remarks/>
        @int,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        percent,
        
        /// <remarks/>
        phone,
        
        /// <remarks/>
        id,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        datetime,
        
        /// <remarks/>
        url,
        
        /// <remarks/>
        email,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class DescribeSObjectResult {
        
        private bool activateableField;
        
        private bool createableField;
        
        private bool customField;
        
        private bool deletableField;
        
        private Field[] fieldsField;
        
        private string labelField;
        
        private string nameField;
        
        private bool queryableField;
        
        private bool retrieveableField;
        
        private bool replicateableField;
        
        private bool searchableField;
        
        private bool updateableField;
        
        private bool undeletableField;
        
        /// <remarks/>
        public bool activateable {
            get {
                return this.activateableField;
            }
            set {
                this.activateableField = value;
            }
        }
        
        /// <remarks/>
        public bool createable {
            get {
                return this.createableField;
            }
            set {
                this.createableField = value;
            }
        }
        
        /// <remarks/>
        public bool custom {
            get {
                return this.customField;
            }
            set {
                this.customField = value;
            }
        }
        
        /// <remarks/>
        public bool deletable {
            get {
                return this.deletableField;
            }
            set {
                this.deletableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", IsNullable=true)]
        public Field[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool queryable {
            get {
                return this.queryableField;
            }
            set {
                this.queryableField = value;
            }
        }
        
        /// <remarks/>
        public bool retrieveable {
            get {
                return this.retrieveableField;
            }
            set {
                this.retrieveableField = value;
            }
        }
        
        /// <remarks/>
        public bool replicateable {
            get {
                return this.replicateableField;
            }
            set {
                this.replicateableField = value;
            }
        }
        
        /// <remarks/>
        public bool searchable {
            get {
                return this.searchableField;
            }
            set {
                this.searchableField = value;
            }
        }
        
        /// <remarks/>
        public bool updateable {
            get {
                return this.updateableField;
            }
            set {
                this.updateableField = value;
            }
        }
        
        /// <remarks/>
        public bool undeletable {
            get {
                return this.undeletableField;
            }
            set {
                this.undeletableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:partner.soap.sforce.com")]
    public partial class LoginResult {
        
        private string serverUrlField;
        
        private string sessionIdField;
        
        private string userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serverUrl {
            get {
                return this.serverUrlField;
            }
            set {
                this.serverUrlField = value;
            }
        }
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:partner.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:partner.soap.sforce.com", IsNullable=false)]
    public partial class QueryOptions : System.Web.Services.Protocols.SoapHeader {
        
        private System.Nullable<int> batchSizeField;
        
        private bool batchSizeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> batchSize {
            get {
                return this.batchSizeField;
            }
            set {
                this.batchSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool batchSizeSpecified {
            get {
                return this.batchSizeFieldSpecified;
            }
            set {
                this.batchSizeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:partner.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:partner.soap.sforce.com", IsNullable=false)]
    public partial class CallOptions : System.Web.Services.Protocols.SoapHeader {
        
        private string clientField;
        
        /// <remarks/>
        public string client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:partner.soap.sforce.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:partner.soap.sforce.com", IsNullable=false)]
    public partial class SaveOptions : System.Web.Services.Protocols.SoapHeader {
        
        private bool autoAssignField;
        
        private string assignmentRuleIdField;
        
        /// <remarks/>
        public bool autoAssign {
            get {
                return this.autoAssignField;
            }
            set {
                this.autoAssignField = value;
            }
        }
        
        /// <remarks/>
        public string assignmentRuleId {
            get {
                return this.assignmentRuleIdField;
            }
            set {
                this.assignmentRuleIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void describeSObjectCompletedEventHandler(object sender, describeSObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class describeSObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal describeSObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DescribeSObjectResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DescribeSObjectResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void describeGlobalCompletedEventHandler(object sender, describeGlobalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class describeGlobalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal describeGlobalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DescribeGlobalResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DescribeGlobalResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void createCompletedEventHandler(object sender, createCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void updateCompletedEventHandler(object sender, updateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SaveResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SaveResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void deleteCompletedEventHandler(object sender, deleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void retrieveCompletedEventHandler(object sender, retrieveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getDeletedCompletedEventHandler(object sender, getDeletedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDeletedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDeletedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDeletedResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDeletedResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getUpdatedCompletedEventHandler(object sender, getUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUpdatedResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUpdatedResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void queryCompletedEventHandler(object sender, queryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void queryMoreCompletedEventHandler(object sender, queryMoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryMoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryMoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void searchCompletedEventHandler(object sender, searchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getServerTimestampCompletedEventHandler(object sender, getServerTimestampCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getServerTimestampCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getServerTimestampCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetServerTimestampResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetServerTimestampResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void setPasswordCompletedEventHandler(object sender, setPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetPasswordResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetPasswordResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void resetPasswordCompletedEventHandler(object sender, resetPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResetPasswordResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResetPasswordResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getUserInfoCompletedEventHandler(object sender, getUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserInfoResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserInfoResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591